leader: true

main:
  leader:
    velocity:
      server: "./server/velocity/"
      logs: "./server/velocity/logs/"
      image: "minecraft:17-alpine"
      net: "mc-net"
      ipv4: "172.10.0.1"
      ports:
        - "25565" # java
        - "udp:19132" # bedrock
      startup: true
    auth:
      server: "./server/primary/auth/"
      logs: "./server/primary/auth/logs/"
      image: "minecraft:17-alpine"
      net: "mc-net"
      startup: true
    oneblock:
      server: "./server/oneblock/"
      logs: "./server/oneblock/logs/"
      image: "minecraft:17-alpine"
      net: "mc-net"
      startup: true

hub:
  leader:
    "1":
      server: "./server/primary/hub_1/"
      logs: "./server/primary/hub_logs/hub_1/"
      image: "minecraft:17-alpine"
      net: "mc-net"
      world: "world_1"
      startup: true
    "2":
      server: "./server/primary/hub_1/"
      logs: "./server/primary/hub_logs/hub_2/"
      image: "minecraft:17-alpine"
      net: "mc-net"
      world: "world_2"
      startup: false

bedwars:
  leader:
    lobby_1:
      server: "./server/bedwars/lobby_1/"
      logs: "./server/bedwars/lobby_logs/lobby_1/"
      image: "minecraft:17-alpine"
      net: "mc-net"
      world: "world_1"
      startup: true
    lobby_2:
      server: "./server/bedwars/lobby_1/"
      logs: "./server/bedwars/lobby_logs/lobby_2/"
      image: "minecraft:17-alpine"
      net: "mc-net"
      world: "world_2"
      startup: false
    lobby_3:
      server: "./server/bedwars/lobby_1/"
      logs: "./server/bedwars/lobby_logs/lobby_3/"
      image: "minecraft:17-alpine"
      net: "mc-net"
      world: "world_3"
      startup: false
  worker:
    instance:
      server: "./server/bedwars/game/"
      logs: "./server/bedwars/instance_logs/{name}"
      image: "minecraft:17-alpine"
      net: "mc-net"